### ISSUE TITLE
Plotting does not work with newer Matplotlib.

### ISSUE THREAD

**Issue by aleksandrbazhin** [aleksandrbazhin/ellipsoid_fit_python#9]
Running plot_ellipsoid.py causes
```
Traceback (most recent call last):
  File "plot_ellipsoid.py", line 29, in <module>
    ax.set_aspect('equal')
  File "C:\Python37\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 324, in set_aspect
    "Axes3D currently only supports the aspect argument "
```
Tested on Python 3.7.3 and Matplotlib 3.3.3
Everything works with Python 3.5.3 and Matplotlib 2.2.0.

**Comment by aleksandrbazhin** [comment]
Looks like they removed it from Matplotlib https://github.com/matplotlib/matplotlib/issues/1077/
